### ISSUE TITLE
SemanticTextAnnotatorSpecial.php: Call to undefined method OutputPage::addWikiText()

### ISSUE THREAD

**Issue by LCavalini** [TobiasWeller/SemanticTextAnnotator#10]
**Setup**
- MediaWiki: 1.34.0-alpha
- PHP: 7.3.5 (apache2handler)
- MariaDB: 10.1.40-MariaDB
- ICU: 63.1
- PageForms: 4.5.1
- Semantic Mediawiki: 3.0.2
- Semantic TextAnnotator: 0.72

When I access the special page _Special:SemanticTextAnnotator_, I get this error message:

```
[c3c2f700ba81758ea3bb7e9c] /ec-wiki/index.php/Especial:SemanticTextAnnotator Error from line 45 of D:\xampp\htdocs\ec-wiki\extensions\SemanticTextAnnotator\specials\SemanticTextAnnotatorSpecial.php: Call to undefined method OutputPage::addWikiText()

Backtrace:

#0 D:\xampp\htdocs\ec-wiki\includes\specialpage\SpecialPage.php(571): SemanticTextAnnotatorSpecial->execute(NULL)
#1 D:\xampp\htdocs\ec-wiki\includes\specialpage\SpecialPageFactory.php(582): SpecialPage->run(NULL)
#2 D:\xampp\htdocs\ec-wiki\includes\MediaWiki.php(296): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#3 D:\xampp\htdocs\ec-wiki\includes\MediaWiki.php(892): MediaWiki->performRequest()
#4 D:\xampp\htdocs\ec-wiki\includes\MediaWiki.php(523): MediaWiki->main()
#5 D:\xampp\htdocs\ec-wiki\index.php(42): MediaWiki->run()
#6 {main}
```

I can see Annotate link on every page, but MediaWiki says "You have not yet installed the Extension. Please go to Special Page" when I click on it.

**Comment by LCavalini** [comment]
It seems that _OutputPage::addWikiText()_ method is not available in MediaWiki 1.34-so I just replaced it by _OutputPage::addWikiTextAsInterface()_. Now it works perfectly.
