### ISSUE TITLE
Error to access Special Page - Semantic Text Annotator

### ISSUE THREAD

**Issue by lotusccong** [TobiasWeller/SemanticTextAnnotator#11]
I installed the Semantic Text Annotator in Mediawiki 1.36.1, PHP 7.4.20, Semantic Mediawiki 3.2.3 and Page forms 4.9.5., Semantic Text Annotator 0.7.2

When I access the Special page at Semantic Text Annotator, I got this error -

2ca6e462371145fd88cd9410] /wiki/index.php/Special:SemanticTextAnnotator Error: Call to undefined method OutputPage::addWikiText()

Backtrace:

from D:\Bitnami\mediawiki-1.36.1-0\apps\mediawiki\htdocs\extensions\SemanticTextAnnotator\specials\SemanticTextAnnotatorSpecial.php(45)

#0 D:\Bitnami\mediawiki-1.36.1-0\apps\mediawiki\htdocs\includes\specialpage\SpecialPage.php(646): SemanticTextAnnotatorSpecial->execute()

#1 D:\Bitnami\mediawiki-1.36.1-0\apps\mediawiki\htdocs\includes\specialpage\SpecialPageFactory.php(1386): SpecialPage->run()

#2 D:\Bitnami\mediawiki-1.36.1-0\apps\mediawiki\htdocs\includes\MediaWiki.php(309): MediaWiki\SpecialPage\SpecialPageFactory->executePath()

#3 D:\Bitnami\mediawiki-1.36.1-0\apps\mediawiki\htdocs\includes\MediaWiki.php(913): MediaWiki->performRequest()

#4 D:\Bitnami\mediawiki-1.36.1-0\apps\mediawiki\htdocs\includes\MediaWiki.php(546): MediaWiki->main()

#5 D:\Bitnami\mediawiki-1.36.1-0\apps\mediawiki\htdocs\index.php(53): MediaWiki->run()

#6 D:\Bitnami\mediawiki-1.36.1-0\apps\mediawiki\htdocs\index.php(46): wfIndexMain()

#7 {main}

May I know what is the recommended Mediawiki version I should use  Semantic Text Annotator ? 1.36.X or 1.35.X or 1.27.X ?
How about SMW version ?

**Comment by krabina** [comment]
I would recommend MediaWiki 1.35.X and the current version of SMW, since 1.36 is not supported by SMW yet.

**Comment by krabina** [comment]
btw. this fork is ahead, so it might be worth asking there: https://github.com/martiniusDE/SemanticTextAnnotator

**Comment by lotusccong** [comment]
I am using MediaWiki 1.35.X . Same error message even used  https://github.com/martiniusDE/SemanticTextAnnotator,

**Comment by krabina** [comment]
I doubt it has to do with SMW. The error is using an outdated call to a funtion of MediaWiki, see 
https://www.mediawiki.org/wiki/Topic:Vsdkqobtrag4802t and https://phabricator.wikimedia.org/rEPFM59c1d49f8d43af087eed9d3868576155b91e8125
If you have the nerve, you could try it in MW 1.31 and SMW 3.2.x

**Comment by aliciuki** [comment]
Hello!
I just installed Semantic Text Annotator with the following software versions:
MediaWiki 1.35.2
PHP 7.4.3 (apache2handler)
Semantic Text Annotator 0.7.2 
Semantic MediaWiki 3.2.3
Page Forms 5.2.1 (29bbbee)

While the Version pages shows the Semantic Text Annotator as installed, and the link appears under Special Pages, clicking on the link leads to an 'Internal Error' site:
**[42b6d82971acc28c458350e7] 2021-09-16 21:38:11: Fatal exception of type "Error"**

1. I followed the installation guide to the letter. Is there an installation step that is obvious but not made explicit in the instructions provided? (I'm fairly inexperienced)
2. Are there any known conflicts with other extensions?
Thank you for your help!

**Comment by krabina** [comment]
This could be related to PageForms, see https://phabricator.wikimedia.org/T228048
Or you could try this on SemanticTextAnnotatorSpecial.php https://www.mediawiki.org/wiki/Topic:Vsdkqobtrag4802t
